runtime: python311
entrypoint: gunicorn -k uvicorn.workers.UvicornWorker -w 2 -b :$PORT main:app
automatic_scaling:
  min_instances: 0
  max_instances: 1
env_variables:
  MODEL_GCS_URI: "gs://fiery-rarity-models/models/model.pkl"
